config/routes.rb
Rails.application.routes.draw do

  resources :students do
    resources :addresses
  end
  resources :courses
  
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :student

  validates_presence_of :description
  validates_presence_of :street_address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip_code

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord

  has_many :student_courses
  has_many :students, through: :student_courses

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :addresses
  has_many :student_courses
  has_many :courses, through: :student_courses

  validates_presence_of :name

end

app/models/student_course.rb
class StudentCourse < ApplicationRecord

  belongs_to :course
  belongs_to :student

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @student = Student.find(params[:student_id])
    @address = Address.new
  end

  def create
    student = Student.find(params[:student_id])
    @address = student.addresses.new(address_params)
    if @address.save
      redirect_to student_path(@address.student_id)
    else
      render new
    end
  end

  private

  def address_params
    params.require(:address).permit(:description, :street_address, :city, :state, :zip_code)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    @course = Course.find(params[:id])
    @students = @course.students
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def show
    @student = Student.find(params[:id])
    @addresses = @student.addresses
    @courses = @student.courses
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :new
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(student_params)
    if @student.save
      redirect_to student_path(@student)
    else
      render :edit
    end
  end

  def destroy
    Student.destroy(params[:id])
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/new.html.erb
<h2>Create a New Address</h2>

<%= form_for [@student, @address] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>

  <%= f.submit %>
<% end %>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>

<%= @students.each do |student| %>
  <p><%= student.name %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Students</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <%= link_to 'See All Students', students_path %>
      <%= link_to 'Create New Student', new_student_path %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h2>Edit Student</h2>

<%= form_for [@student] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/index.html.erb
<h1>All Students</h1>

<% @students.each do |student| %>
  <%= link_to student.name, student_path(student) %>
  <%= link_to "Delete", student_path(student), method: 'delete' %>
<% end %>

app/views/students/new.html.erb
<h2>Create a New Student</h2>

<%= form_for [@student] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/students/show.html.erb
<h2><%= @student.name %></h2>

<%= @addresses.each do |address|%>
  <p><%= address.description %></p>
  <p><%= address.street_address %></p>
  <p><%= address.city %></p>
  <p><%= address.state %></p>
  <p><%= address.zip_code %></p>
<% end %>

<%= @courses.each do |course| %>
  <p><%= course.name %></p>
<% end %>